version: '2'

services:

  mongodb:
    image: mongo:3.0
    volumes:
     - ./tmp-docker-vol/mongodb:/data/db

  micro-comments:
    build: .
    #tty: true
    #command: bash
    command: ./docker/run.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
    environment:
      - ENV=local
