version: '2'

services:

  micro-comments:
    build: .
    #tty: true
    #command: bash
    command: python -u ./app/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
     - ./tmp-docker-vol/mongodb:/data/db


